name: Xavier Granada
favicon: null
layout_spectrum: 0.2873730973806232
typography_spectrum: 0.23819071683101356
title: 'Film & TV  Executive Producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5204675786662847
  lightness: 0.4691999803762883
  saturation: 0.6997655236627907
  rhythmicContrast: 0.7138781207613647
purpose: []
